# Generated by Django 3.2.9 on 2021-12-02 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationBlood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=50)),
                ('bloodweight', models.CharField(choices=[('450ml', '1 bag'), ('900ml', '2 bag'), ('1350ml', '3 bag'), ('1800ml', '4 bag'), ('2250ml', '5 bag'), ('2700ml', '6 bag')], max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=50)),
                ('adreess', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('apply_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllDonar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgroup', models.CharField(default=0, max_length=50)),
                ('district', models.CharField(default=0, max_length=250)),
                ('phone', models.CharField(default=0, max_length=50)),
                ('email', models.EmailField(default=0, max_length=254)),
                ('last_donate', models.DateField(default=0)),
                ('age', models.CharField(default=0, max_length=50)),
                ('address', models.CharField(default=0, max_length=250)),
                ('dob', models.DateField(default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='donar image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
