# Generated by Django 3.2.9 on 2021-12-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldonar',
            name='image',
            field=models.ImageField(default=0, upload_to='donar image'),
        ),
    ]
