# Generated by Django 3.2.9 on 2021-12-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donarapp', '0002_alter_alldonar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='alldonar',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='alldonar',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alldonar',
            name='bloodgroup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alldonar',
            name='district',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='alldonar',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alldonar',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='alldonar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donar image'),
        ),
        migrations.AlterField(
            model_name='alldonar',
            name='last_donate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alldonar',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
