# Generated by Django 3.2.9 on 2021-12-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donarapp', '0003_auto_20211203_0120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewModel',
        ),
    ]
