# Generated by Django 3.2.9 on 2021-12-02 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donarapp', '0004_delete_newmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alldonar',
            name='image',
        ),
    ]
