# Generated by Django 3.2.9 on 2021-12-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donarapp', '0005_remove_alldonar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alldonar',
            name='address',
        ),
        migrations.RemoveField(
            model_name='alldonar',
            name='age',
        ),
        migrations.RemoveField(
            model_name='alldonar',
            name='district',
        ),
        migrations.RemoveField(
            model_name='alldonar',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='alldonar',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alldonar',
            name='last_donate',
        ),
        migrations.RemoveField(
            model_name='alldonar',
            name='phone',
        ),
    ]
