# Generated by Django 3.2.9 on 2021-12-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donarapp', '0007_auto_20211203_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldonar',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='profile pic'),
            preserve_default=False,
        ),
    ]
