# Generated by Django 3.2.9 on 2021-12-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donarapp', '0008_alldonar_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
