# Generated by Django 3.2.9 on 2022-01-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donarapp', '0009_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AlterField(
            model_name='alldonar',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile pic'),
        ),
    ]
