# Generated by Django 3.2.9 on 2022-01-28 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donarapp', '0010_auto_20220128_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllDonar',
        ),
    ]
