# Generated by Django 3.2.9 on 2022-02-02 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Donarapp', '0011_delete_alldonar'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedBlood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=50)),
                ('bloodweight', models.CharField(choices=[('450ml', '1 bag'), ('900ml', '2 bag'), ('1350ml', '3 bag'), ('1800ml', '4 bag'), ('2250ml', '5 bag'), ('2700ml', '6 bag')], max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=50)),
                ('adreess', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('apply_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
