# Generated by Django 3.2.9 on 2022-02-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donarapp', '0012_needblood'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationblood',
            name='done_status',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='donationblood',
            name='status',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
