# Generated by Django 3.2.9 on 2022-02-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donarapp', '0013_auto_20220202_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationblood',
            name='done_status',
        ),
        migrations.RemoveField(
            model_name='donationblood',
            name='status',
        ),
        migrations.RemoveField(
            model_name='needblood',
            name='status',
        ),
    ]
