# Generated by Django 3.2.9 on 2022-02-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donarapp', '0014_auto_20220202_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationblood',
            name='done_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationblood',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='needblood',
            name='done_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='needblood',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
