# Generated by Django 3.2.9 on 2022-02-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donarapp', '0015_auto_20220202_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationblood',
            name='action',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
