# Generated by Django 3.2.9 on 2022-02-02 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Donarapp', '0017_remove_donationblood_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(choices=[('blood', 'blood'), ('sports', 'sports'), ('funny', 'funny'), ('adult', 'adult'), ('notice', 'notice')], max_length=50)),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('upload_pic', models.ImageField(upload_to='BlogPost')),
                ('check_status', models.BooleanField(default=False)),
                ('approved_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
