# Generated by Django 3.2.9 on 2022-08-22 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Donarapp', '0020_creatpost_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creatpost',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='creatpost',
            name='date',
        ),
        migrations.AddField(
            model_name='creatpost',
            name='creat_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
