# Generated by Django 3.2.9 on 2022-08-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donarapp', '0021_auto_20220822_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatpost',
            name='creat_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
